version: "3.8"
services:
    nodeserver:
        build:
            context: ./app
        ports:
            - "5000:5000"
          
    reactapp:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        depends_on: 
            - nodeserver
        links:
            - nodeserver

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"

